DROP TABLE IF EXISTS CIRCUIT_PLACE;

CREATE TABLE CIRCUIT_PLACE
(
CIRCUIT_ID int,
PLACE_ID int,
PRIMARY KEY(CIRCUIT_ID,PLACE_ID),
FOREIGN KEY(CIRCUIT_ID) REFERENCES CIRCUITS(CIRCUIT_ID) ON DELETE CASCADE,
FOREIGN KEY(PLACE_ID) REFERENCES PLACES(PLACE_ID) ON DELETE CASCADE
);