DROP TABLE IF EXISTS SPOT_TAG;

CREATE TABLE SPOT_TAG
(
SPOT_ID int,
TAG_ID int,
PRIMARY KEY(SPOT_ID,TAG_ID),
FOREIGN KEY(SPOT_ID)REFERENCES SPOTS(SPOT_ID) ON DELETE CASCADE,
FOREIGN KEY (TAG_ID) REFERENCES TAGS(TAG_ID) ON DELETE CASCADE
);