
DROP TABLE IF EXISTS `STATE` ;



CREATE TABLE `state` 
(
  
`STATE_ID` int PRIMARY KEY AUTO_INCREMENT,
`NAME` varchar(20) NOT NULL,
`REVIEW` text NOT NULL,
  
`DESCRIPTION` longtext NOT NULL,
`RATING` int NOT NULL
);



--
-- Dumping data for table `state2`
--



INSERT INTO `state` (`STATE_ID`,`NAME`, `REVIEW`, `DESCRIPTION`,`RATING`) VALUES

(1,'ARUNACHAL PRADESH', '', 'Arunachal Pradesh, North east India\'s remotest state, also known as \'Land of the Dawn-lit-Mountains\'  is the first Indian soil to greet the morning sun. Arunachal Pradesh is the northeastern tip of India with its borders touching China, Bhutan and Burma (Myanmar). Towards the south is Assam and Nagaland. Arunachal offers a dazzling array of flora and fauna that is sure to enchant any tourist. The state is proud of having more than 500 rare species of Orchids.\r\n\r\nArunachal Pradesh\'s mysterious, powerful and beautiful rivers with faces and moods that change dramatically ever so often form the colorful lifelines. These are ideal for rafting and angling and the rugged terrain is ideal for trekking, hiking and holidaying in a serene atmosphere. River Rafting routes include Kameng (Seppa- Bhalukpung), Subansiri (Taliha- North of Daporijo), Siang (entire course), Dibang (Anini- Assam Border). ',4.5),

(2,'ASSAM', '', 'Assam is one of the eight states in the Northeastern part of India. It is comprised mostly of the valleys of Brahmaputra and Barak. Assam and the rest of the Northeastern states are connected to the rest of the country via the Siliguri Corridor or the Chicken\'s Neck, a 22-kilometre small strip of land in West Bengal. Its other name is the Gateway to the Northeast, as it is the main connection to reach the other states in the Northeastern part of the country. The state also shares an international border with Bhutan and Bangladesh. The people, culture and traditions of Assam are similar to that of the South Eastern countries.',4.5),

(3,'MANIPUR', '', 'Manipur literally meaning “A jeweled land” nestle deep within a lush green corner of North East India. It seems much like an exquisite  work of art  executed by superb hands of Nature and is indeed a state of exquisite natural beauty and splendors, the beauty of which once inspired Mrs. St. Clair Grimwood described it as “A Pretty Place more beautiful than many show places of the world” Late Pandit Jawaharlal Nehru paid a fitting tribute by describing it as “Jewel of India”.\r\n\r\nSurrounded by blue hills with an oval shaped valley at the centre, rich in art and tradition and surcharged with nature’s pristine glory. Manipur lies on a melting pot of culture. It is birth place of Polo. This is the place  where Rajashree Bhagyachandra created the famous Ras Lila, the classical dance of Manipur, out of his enchanting dream by the grace of Lord Krishna.\r\n\r\nHer folk dances reveal the mythological concept of creation of Manipur.\r\n\r\nHaving a varied and proud history from the earliest times, Manipur came under the British Rule as a Princely State after the defeat in the Anglo-Manipuri War of 1891. After independence of India in 1947, the Princely State of Manipur was merged in the Indian Union on October 15,1949 and became a full-fledged State of India on the 21th January, 1972 with a Legislative Assembly of 60 seats of which 20 are reserved for Scheduled Tribe and 1 reserved for Scheduled Caste. The State is represented in the Lok Sabha by two members and by one member in the Rajya Sabha.',4.5),

(4,'MEGHALAYA', '', 'Meghalaya or megh- cloud; alay- home; is a picturesque but tiny state in the northeastern region of India. As the state remained cut off from mainstream India for a long time due to some ethnic problems, it has been able to survive the onslaught of crass commercialization that has taken over other famous tourist centers of India. As is the name, the state receives heavy rainfall and two of the world’s wettest places are located in Meghalaya. Full of vibrant culture, tradition, great scenicbeauty, and tranquility are some of the attractions of the state that can pull any tourist in.',4.5),

(5,'MIZORAM', '', 'Mizoram is one of the seven sisters of Northeast India, bordered by Myanmar (formerly known as Burma) to its east and south, Bangladesh to its west, and the states of Manipur, Assam, and Tripura to its north. \r\nMizoram means \'Land of the Highlanders\' and its local language is Mizo. The Mizo Hills, which dominate the state\'s topography, rise to more than 2000 m (6560 ft) near the Myanmar border. Aizawl, the state capital, is 1220 m (4000 ft) above sea level.\r\n\r\nAn amalgam of the former North and South Lushai Hill districts, Mizoram is a land of great natural beauty, an endless variety of landscape with rich flora and fauna, clusters of whispering pines and quaint villages with houses on stilts.\r\n\r\nThe Tropic of Cancer runs through the heart of Mizoram, and hence, it has a pleasantly temperate climate throughout the year. A land of steep hills and deep gorges, Mizoram\'s highest peak \'The Blue Mountain\' rises to a height of 2165 metres. Important rivers that flow through this hilly state are Tlawang, Sonai, Tuivawl, Kolodine and Kamaphuli.\r\n\r\nThe hilly city Aizawl, located nearly 4,000 feet above sea-level, is a religious and cultural centre of Mizoram where indigenous handicrafts are also available. You will find Champhai, a beautiful resort on the Myanmar border. Tamdil, a natural lake with virgin forest, is 60 km from Aizawl and 10 km from tourist resort of Saitual, Vantawng falls, five km from hill station. Vantawng is the highest and most beautiful waterfalls in Mizoram. The department of tourism has opened tourist lodge at Aizawl, Lunglei, Champhai and wayside restaurant at Thingdawl, Hnahthial, recreational centre at Beraw Tiang and Alpine picnic hut at District Park near Zobawk. ',4.5),

(6,'NAGALAND', '', 'It is a land of folklore passed down the generations through word of mouth. Here, music is an integral part of life; folk songs eulogising ancestors, the brave deeds of warriors and traditional heroes; poetic love songs immortalising ancient tragic love stories; Gospel songs that touch your soul (should you have a religious bend of mind) or the modern tunes rendered exquisitely to set your feet a-tapping.\r\nEach of the 16 odd tribes and sub-tribes that dwell in this exotic hill State can easily be distinguished by the colourful and intricately designed costumes, jewellery and beads that they adorn. The present generation of Nagas have ventured into fashion designing in a big way, reproducing fabrics that represent the ancestral motifs blended with modern appeal. Indeed, it is a beautiful mix of the past with the present,a paradise for those who are into fashion designing. This is an affluent fashion station of the East.\r\nThe traditional ceremonial attire of each tribe is in itself, an awe inspiring sight to behold; the multicoloured spears and daos decorated with dyed goats hair, the headgear made of finely woven bamboo interlaced with orchid stems, adorned with boar\'s teeth and hornbill\'s feathers, elephant tusk armlets. In days of yore every warrior had to earn each of these items through acts of valour, to wear them.\r\nNature could not have been kinder to Nagaland, sometimes referred to as the Switzerland of the East; the exquisitely picturesque landscapes, the vibrantly colourful sunrise and sunset, lush and verdant flora, this is a land that represents unimaginable beauty, moulded perfectly for a breath taking experience.',4.5),

(7,'SIKKIM', '', 'Sikkim has been given many names. The Lepchas, original inhabitants of the land called it Nye-mae-el `paradise\'. The Limbus named it Su Khim or `new house\' while to the Bhutias it was Beymul Demazong `the hidden valley of rice\'.\r\nToday, travelers embarking on a journey of Sikkim discover a mystical wonderland of spectacular natural beauty. The panoramic perfection of the snow-capped Himalayas, the heady scent of flower-bedecked meadows, the vibrant culture and joyous festivals, the infinite variety of its flora and fauna makes it a holiday that is at once fascinating and challenging.\r\nThe crowning glory of Sikkim is Mt. Khangchendzonga, the third highest mountain in the world. With magnificent snow and ice scenery it is often regarded as the undisputed monarch among the peaks of the world. But for the Sikkimese Khangchendzonga is much more than a mountain and is revered as the abode of their guardian deity Dzo-nga.\r\nEven today the mountain god is invoked and prayed to during Pang Lhabsol, a major Sikkimese festival, which also commemorates the blood brotherhood sworn between the Lepchas and the Bhutias at Kabi in the fifteenth century. The sacred mountain can be viewed from every corner of Sikkim and remains an intrinsic part of the consciousness of the people.\r\nSikkim shares its border with Nepal in the west and Bhutan in the east, with the Tibetan plateau rising from its northern border. It was once a Himalayan monarchy and part of the fabled Silk Route to China. Its merger with India in 1975 has offered a window to the world to discover the treasures of this hidden land. ',4.5),
(8,'TRIPURA', '', 'Tripura, one of the north-eastern states, is bounded on the north, west, south and southeast by Bangladesh, whereas in the east, it shares a common boundary with Assam and Mizoram.\r\nWith its pleasant climate and scenic landscape, Tripura is a favoured tourist destination. The state offers tourists attractions such as historical Hindu and Buddhist sites, temples, rivers and rock carvings',4.5);


